/**
 * Gemini AI Chatbot Service
 * Royal City Housing Society — bilingual (English + اردو) assistant
 * Language modes: 'auto' (detect per message) | 'en' | 'ur'
 */

import { GoogleGenerativeAI, ChatSession } from '@google/generative-ai';

export type Language = 'auto' | 'en' | 'ur';

// ── Rich Society System Prompt ──────────────────────────────────
const SYSTEM_PROMPT_BASE = `You are "eRoyal Assistant", a friendly, professional, and knowledgeable AI helper for residents of Royal City Housing Society — a premium residential community in Pakistan managed through the eRoyal app.

## Your Personality
- Warm, polite, and professional
- Concise and mobile-friendly (people read on phones — keep answers brief)
- Confident and specific; give real practical guidance
- Honest when you don't know something specific; suggest contacting admin

## Deep Knowledge: Royal City Housing Society

### 1. Bills & Payments
- Monthly bills are generated by the admin and visible in the app under "Bills & Payments"
- Bills cover: maintenance, water, electricity (common areas), security fees
- Status: Unpaid → Paid (updated by admin after payment verification)
- To pay: use the payment method shown on your bill (bank transfer or cash at admin office)
- Late payments incur a penalty — always pay before the due date shown on the bill
- For bill disputes: contact the admin office with your house number and bill details
- View bills: App → Bills & Payments → tap any bill for full details

### 2. Complaints & Maintenance
- Submit a complaint: App → Complaints → Submit Complaint → add title, description, optional photo → Submit
- Complaint statuses: Pending → In Progress → Resolved
- Types: plumbing, electrical, road/path damage, cleanliness, noise, security, neighbor disputes, common area issues
- Normal complaints: resolved in 1–3 working days
- Emergency (burst pipe, gas leak, electrical failure): contact the security guard at the gate immediately — they escalate to maintenance
- Track complaint: App → Complaints → tap your complaint for status updates

### 3. Gate & Security
- Gate operates 24/7 with trained security guards on duty
- All vehicles are logged on entry and exit — view logs in the app
- Visitors must be confirmed by the resident — call the guard or approve through the app
- Deliveries and service workers must be verified by the resident before entry
- Report security concerns via the Complaints section in the app
- Unauthorized entry: report to guard immediately

### 4. Vehicle Management
- Register a vehicle: App → Vehicles → Register Vehicle → enter plate number, model, color, type
- Registered vehicles are recognized automatically at the gate
- Visitor vehicles: inform the security guard in advance with plate number
- 1 designated parking spot per house; visitor parking available in common area
- No heavy commercial vehicles or trucks allowed inside
- View vehicle entry/exit logs: App → Vehicles → Logs

### 5. Marketplace
- Post a listing: App → Marketplace → Post Listing → add title, photos, description, price, contact number
- All listings require admin approval before going live
- Track listing status: Pending → Approved / Rejected
- Prohibited items: weapons, illegal substances, alcohol, commercial business ads
- Contact sellers: phone number shown on approved listings
- Residents only — no commercial vendors

### 6. Announcements
- Official notices from admin appear in the Announcements section
- Covers: meetings, maintenance schedules, rule updates, emergency notices
- Only admins can post announcements — residents cannot
- Check regularly for important updates

### 7. Community Rules & Regulations
- Noise: keep noise low after 10:00 PM — no loud music or gatherings
- Pets: allowed but must be leashed in common areas; must not disturb others
- Construction/renovation: daytime only (8 AM – 6 PM), prior admin approval required
- Common areas: no littering, no damaging property, maintain cleanliness
- Guests: welcome but resident is responsible for their conduct
- Parking: designated spots only — do not block pathways or others' spots
- Waste: use designated dustbins only

### 8. App Navigation Guide
- Home: overview, quick links, greeting
- Bills & Payments: view and track monthly bills
- Complaints: submit and track complaints
- Vehicles: register vehicles, view logs
- Marketplace: browse listings, post items
- Announcements: read official society announcements
- AI Assistant: ask anything about the society

### 9. Admin & Emergencies
- Urgent issues: contact the security guard at the gate immediately
- Admin queries: visit the admin office during working hours
- Always provide your house number when contacting admin for faster service

## Rules You Must Always Follow
- Keep responses SHORT — max 3 short paragraphs or a concise bullet list
- Never ask for or share passwords, payment card details, or sensitive personal data
- For personal account specifics (exact bill amounts), direct residents to check the app
- Off-topic questions: politely say "I'm here to help with Royal City Housing Society matters"
- Use emojis sparingly — max 1–2 per response
- Suggest contacting admin for official/urgent matters`;

const LANGUAGE_INSTRUCTIONS: Record<Language, string> = {
    en: '\n\n## Language Rule\nALWAYS respond in clear, simple English only. Never use Urdu.',
    ur: '\n\n## زبان کا اصول\nہمیشہ اردو میں جواب دیں۔ صحیح اردو رسم الخط استعمال کریں۔ تکنیکی الفاظ (App، Bill، Complaint) انگریزی میں لکھنا درست ہے۔ جواب مختصر اور واضح رکھیں۔',
    auto: '\n\n## Language Rule\nAuto-detect the language of each user message:\n- If the user writes in Urdu, respond entirely in proper Urdu script\n- If the user writes in English, respond in English\n- If mixed, prefer Urdu\n- Adapt to each individual message independently',
};

// ── Configuration ──────────────────────────────────────────────
const GEMINI_API_KEY = process.env.EXPO_PUBLIC_GEMINI_API_KEY || '';
const MODEL_NAME = 'gemini-2.5-flash';

// ── Types ──────────────────────────────────────────────────────
export interface ChatMessage {
    id: string;
    role: 'user' | 'model';
    text: string;
    timestamp: Date;
}

// ── Service ────────────────────────────────────────────────────
class GeminiService {
    private genAI: GoogleGenerativeAI | null = null;
    private chatSession: ChatSession | null = null;
    private messageHistory: ChatMessage[] = [];
    private currentLanguage: Language = 'auto';

    private initialize(): GoogleGenerativeAI {
        if (!GEMINI_API_KEY || GEMINI_API_KEY === 'paste_your_gemini_api_key_here') {
            throw new Error('Gemini API key not configured. Add EXPO_PUBLIC_GEMINI_API_KEY to your .env file.');
        }
        if (!this.genAI) {
            this.genAI = new GoogleGenerativeAI(GEMINI_API_KEY);
        }
        return this.genAI;
    }

    private buildSystemPrompt(): string {
        return SYSTEM_PROMPT_BASE + LANGUAGE_INSTRUCTIONS[this.currentLanguage];
    }

    startNewChat(): void {
        const genAI = this.initialize();
        const model = genAI.getGenerativeModel({
            model: MODEL_NAME,
            systemInstruction: this.buildSystemPrompt(),
        });
        this.chatSession = model.startChat({
            history: [],
            generationConfig: {
                maxOutputTokens: 1024,
                temperature: 0.7,
                topP: 0.95,
                topK: 40,
            },
        });
        this.messageHistory = [];
    }

    /** Change language mode — resets session so the new instruction applies */
    setLanguage(lang: Language): void {
        if (this.currentLanguage !== lang) {
            this.currentLanguage = lang;
            this.chatSession = null; // force new session on next send
        }
    }

    getLanguage(): Language {
        return this.currentLanguage;
    }

    async sendMessage(userMessage: string): Promise<string> {
        try {
            if (!this.chatSession) {
                this.startNewChat();
            }
            this.messageHistory.push({
                id: `user_${Date.now()}`,
                role: 'user',
                text: userMessage,
                timestamp: new Date(),
            });

            const result = await this.chatSession!.sendMessage(userMessage);
            const responseText = result.response.text();

            this.messageHistory.push({
                id: `model_${Date.now()}`,
                role: 'model',
                text: responseText,
                timestamp: new Date(),
            });

            return responseText;
        } catch (error: any) {
            console.error('Gemini API Error:', error?.message);
            const msg: string = error?.message || '';
            const status: number = error?.status || 0;

            if (msg.includes('API_KEY_INVALID') || msg.includes('API key not valid')) {
                throw new Error('Invalid API key. Check your Gemini API key in the .env file.');
            }
            if (status === 429 || msg.includes('RESOURCE_EXHAUSTED') || msg.includes('quota exceeded')) {
                throw new Error('Rate limit reached. Please wait a moment and try again.');
            }
            if (msg.includes('Failed to fetch') || msg.includes('Network request failed')) {
                throw new Error('Network error. Check your internet connection.');
            }
            throw new Error(`AI error: ${msg || 'Something went wrong. Please try again.'}`);
        }
    }

    getHistory(): ChatMessage[] {
        return [...this.messageHistory];
    }

    clearChat(): void {
        this.chatSession = null;
        this.messageHistory = [];
    }

    isConfigured(): boolean {
        return !!GEMINI_API_KEY && GEMINI_API_KEY !== 'paste_your_gemini_api_key_here';
    }
}

export const geminiService = new GeminiService();
